version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
    volumes:
      - dev-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dev-data:
