version: "3"
services:
  postgres:
    image: postgres
    environment:
      # TODO: Change me
      POSTGRES_DB: template
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - service-template

  service-template: # TODO: Change me
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - service-template # TODO: Change me

volumes:
  data:

networks:
  service-template: # TODO: Change me
