apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-service # TODO: Change me
  labels:
    app: template-service # TODO: Change me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-service # TODO: Change me
  template:
    metadata:
      labels:
        app: template-service # TODO: Change me
    spec:
      containers:
        - name: template-service # TODO: Change me
          image: ghcr.io/uptimebeaver/service-template:latest  # TODO: Change me
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
